from django.conf.urls import patterns, url
from school_components import views

urlpatterns = patterns('',
	# students
	url(r'^students/$', 
		'school_components.views.students_view.student_list', 
		name='studentlist'),
	url(r'^students/(?P<student_id>\d+)/$', 
		'school_components.views.students_view.student_list', 
		name='studentlist'),
	url(r'^students/create/$', 
		'school_components.views.students_view.student_create', 
		name='studentcreate'),
	url(r'^students/form/$', 
		'school_components.views.students_view.student_form', 
		name='studentform'),
	url(r'^students/upload/$', 
		'school_components.views.students_view.student_upload', 
		name='studentupload'),
	url(r'^students/export/$', 
		'school_components.views.students_view.student_export', 
		name='studentexport'),

	# parents
	url(r'^parents/$', 
		'school_components.views.parents_view.parent_list', 
		name='parentlist'),
	url(r'^parents/(?P<parent_id>\d+)/$', 
		'school_components.views.parents_view.parent_list', 
		name='parentlist'),
	url(r'^parents/create/$', 
		'school_components.views.parents_view.parent_create', 
		name='parentcreate'),
	url(r'^parents/form/$', 
		'school_components.views.parents_view.parent_form', 
		name='parentform'),

	# courses
	url(r'^courses/$', 
		'school_components.views.courses_view.course_list', 
		name='courselist'),
	url(r'^courses/(?P<course_id>\d+)/$', 
		'school_components.views.courses_view.course_list', 
		name='courselist'),
	url(r'^courses/create/$', 
		'school_components.views.courses_view.course_create', 
		name='coursecreate'),
	url(r'^courses/register/$', 
		'school_components.views.courses_view.course_registration', 
		name='courseregistration'),
	url(r'^courses/register/(?P<course_id>\d+)/$', 
		'school_components.views.courses_view.course_registration', 
		name='courseregistration'),

	# departments
	url(r'^departments/create/$', 
		'school_components.views.courses_view.dept_create', 
		name='deptcreate'),

	# classes
	url(r'^classes/$', 
		'school_components.views.classes_view.class_list', 
		name='classlist'),
	url(r'^classes/(?P<class_id>\d+)/$', 
		'school_components.views.classes_view.class_list', 
		name='classlist'),
	url(r'^classes/create/$', 
		'school_components.views.classes_view.class_create', 
		name='classcreate'),
	url(r'^classes/register/$', 
		'school_components.views.classes_view.class_registration', 
		name='classregistration'),
)